- name: docker build and push
  hosts: ubuntu  
  become: yes  

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes   

    - name: Build Docker Image
      command: docker build -t petstore .
      args:
        chdir: /var/lib/jenkins/workspace/petstore

    - name: tag image
      command: docker tag petstore:latest ankitap1219/petstore:latest 

    - name: Log in to Docker Hub
      community.docker.docker_login:
        registry_url: https://index.docker.io/v1/
        username: ankitap1219
        password: 3YM-F6gGVdbx15130H5eyO116rY

    - name: Push image
      command: docker push ankitap1219/petstore:latest

    - name: Run container
      command: docker run -d --name pet1 -p 8081:8080 ankitap1219/petstore:latest
