---
- name: Docker Build, Tag, Push, and Run
  hosts: localhost 

  tasks:
    - name: Build Docker Image
      docker_image:
        path: /var/lib/jenkins/workspace/javaproject/Ansible
        name: petstore
        tag: latest

    - name: Tag Docker Image
      docker_image:
        name: ankitap1219/petstore
        tag: latest
        source: petstore:latest

    - name: Log in to Docker Hub
      docker_login:
        registry_url: https://index.docker.io/v1/
        username: ankitap1219
        password: 3YM-F6gGVdbx15130H5eyO116rY

    - name: Push Docker Image
      docker_image:
        name: ankitap1219/petstore
        tag: latest
        source: petstore:latest
        push: yes

    - name: Run Docker Container
      docker_container:
        name: pet1
        image: ankitap1219/petstore:latest
        ports:
          - "8081:8080"
        detach: yes
